# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scaffolddatamapperwidget.ui'
#
# Created: Sun Jul  7 12:04:56 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ScaffoldDataMapper(object):
    def setupUi(self, ScaffoldDataMapper):
        ScaffoldDataMapper.setObjectName("ScaffoldDataMapper")
        ScaffoldDataMapper.resize(1235, 904)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ScaffoldDataMapper.sizePolicy().hasHeightForWidth())
        ScaffoldDataMapper.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtGui.QHBoxLayout(ScaffoldDataMapper)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dockWidget = QtGui.QDockWidget(ScaffoldDataMapper)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(418, 135))
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 416, 862))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolBox = QtGui.QToolBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setStyleSheet("QToolBox::tab {\n"
"         background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                     stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                     stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"         border-radius: 5px;\n"
"         color: black;\n"
"     }\n"
"\n"
"     QToolBox::tab:selected { /* italicize selected tabs */\n"
"         font: bold;\n"
"         color: black;\n"
"     }\n"
"QToolBox {\n"
"    padding : 0\n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.parameterFitPage = QtGui.QWidget()
        self.parameterFitPage.setGeometry(QtCore.QRect(0, 0, 412, 798))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameterFitPage.sizePolicy().hasHeightForWidth())
        self.parameterFitPage.setSizePolicy(sizePolicy)
        self.parameterFitPage.setObjectName("parameterFitPage")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.parameterFitPage)
        self.verticalLayout_5.setSpacing(7)
        self.verticalLayout_5.setContentsMargins(0, 3, 0, 3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scaffoldFrame = QtGui.QFrame(self.parameterFitPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaffoldFrame.sizePolicy().hasHeightForWidth())
        self.scaffoldFrame.setSizePolicy(sizePolicy)
        self.scaffoldFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.scaffoldFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.scaffoldFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.scaffoldFrame.setObjectName("scaffoldFrame")
        self.gridLayout_7 = QtGui.QGridLayout(self.scaffoldFrame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.meshType_frame = QtGui.QFrame(self.scaffoldFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meshType_frame.sizePolicy().hasHeightForWidth())
        self.meshType_frame.setSizePolicy(sizePolicy)
        self.meshType_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.meshType_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.meshType_frame.setObjectName("meshType_frame")
        self.formLayout_4 = QtGui.QFormLayout(self.meshType_frame)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setContentsMargins(0, -1, 0, -1)
        self.formLayout_4.setObjectName("formLayout_4")
        self.meshType_label = QtGui.QLabel(self.meshType_frame)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.meshType_label.setFont(font)
        self.meshType_label.setObjectName("meshType_label")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.meshType_label)
        self.meshType_name = QtGui.QLabel(self.meshType_frame)
        self.meshType_name.setText("")
        self.meshType_name.setObjectName("meshType_name")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.meshType_name)
        self.parameterSet_label = QtGui.QLabel(self.meshType_frame)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.parameterSet_label.setFont(font)
        self.parameterSet_label.setObjectName("parameterSet_label")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.parameterSet_label)
        self.species_name = QtGui.QLabel(self.meshType_frame)
        self.species_name.setText("")
        self.species_name.setObjectName("species_name")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.species_name)
        self.ephys_label = QtGui.QLabel(self.meshType_frame)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.ephys_label.setFont(font)
        self.ephys_label.setObjectName("ephys_label")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.ephys_label)
        self.ephys_name = QtGui.QLabel(self.meshType_frame)
        self.ephys_name.setText("")
        self.ephys_name.setObjectName("ephys_name")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.ephys_name)
        self.label = QtGui.QLabel(self.meshType_frame)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label)
        self.gridLayout_7.addWidget(self.meshType_frame, 0, 0, 1, 1)
        self.modifyOptions_frame = QtGui.QFrame(self.scaffoldFrame)
        self.modifyOptions_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.modifyOptions_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.modifyOptions_frame.setObjectName("modifyOptions_frame")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.modifyOptions_frame)
        self.verticalLayout_17.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.timeSeries_groupBox = QtGui.QGroupBox(self.modifyOptions_frame)
        self.timeSeries_groupBox.setEnabled(True)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.timeSeries_groupBox.setFont(font)
        self.timeSeries_groupBox.setObjectName("timeSeries_groupBox")
        self.gridLayout_5 = QtGui.QGridLayout(self.timeSeries_groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.timePoint_label = QtGui.QLabel(self.timeSeries_groupBox)
        self.timePoint_label.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timePoint_label.sizePolicy().hasHeightForWidth())
        self.timePoint_label.setSizePolicy(sizePolicy)
        self.timePoint_label.setObjectName("timePoint_label")
        self.gridLayout_5.addWidget(self.timePoint_label, 0, 0, 1, 1)
        self.timePoint_spinBox = QtGui.QSpinBox(self.timeSeries_groupBox)
        self.timePoint_spinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timePoint_spinBox.sizePolicy().hasHeightForWidth())
        self.timePoint_spinBox.setSizePolicy(sizePolicy)
        self.timePoint_spinBox.setMaximum(1000000000)
        self.timePoint_spinBox.setObjectName("timePoint_spinBox")
        self.gridLayout_5.addWidget(self.timePoint_spinBox, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 1, 1, 1, 1)
        self.verticalLayout_17.addWidget(self.timeSeries_groupBox)
        self.gridLayout_7.addWidget(self.modifyOptions_frame, 1, 0, 1, 1)
        self.transformation_groupBox = QtGui.QGroupBox(self.scaffoldFrame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.transformation_groupBox.setFont(font)
        self.transformation_groupBox.setObjectName("transformation_groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.transformation_groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.position_label = QtGui.QLabel(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.position_label.setFont(font)
        self.position_label.setObjectName("position_label")
        self.gridLayout_2.addWidget(self.position_label, 2, 0, 1, 1)
        self.yaw_doubleSpinBox = QtGui.QDoubleSpinBox(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.yaw_doubleSpinBox.setFont(font)
        self.yaw_doubleSpinBox.setMinimum(-360.0)
        self.yaw_doubleSpinBox.setMaximum(360.0)
        self.yaw_doubleSpinBox.setObjectName("yaw_doubleSpinBox")
        self.gridLayout_2.addWidget(self.yaw_doubleSpinBox, 1, 1, 1, 2)
        self.pitch_label = QtGui.QLabel(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pitch_label.setFont(font)
        self.pitch_label.setObjectName("pitch_label")
        self.gridLayout_2.addWidget(self.pitch_label, 0, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(1000, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 3, 0, 1, 1)
        self.pitch_doubleSpinBox = QtGui.QDoubleSpinBox(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pitch_doubleSpinBox.setFont(font)
        self.pitch_doubleSpinBox.setMinimum(-360.0)
        self.pitch_doubleSpinBox.setMaximum(360.0)
        self.pitch_doubleSpinBox.setObjectName("pitch_doubleSpinBox")
        self.gridLayout_2.addWidget(self.pitch_doubleSpinBox, 1, 3, 1, 1)
        self.rotateAxis_label = QtGui.QLabel(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.rotateAxis_label.setFont(font)
        self.rotateAxis_label.setObjectName("rotateAxis_label")
        self.gridLayout_2.addWidget(self.rotateAxis_label, 0, 0, 1, 1)
        self.yaw_label = QtGui.QLabel(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.yaw_label.setFont(font)
        self.yaw_label.setObjectName("yaw_label")
        self.gridLayout_2.addWidget(self.yaw_label, 0, 1, 1, 2)
        self.roll_label = QtGui.QLabel(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.roll_label.setFont(font)
        self.roll_label.setObjectName("roll_label")
        self.gridLayout_2.addWidget(self.roll_label, 0, 4, 1, 1)
        self.roll_doubleSpinBox = QtGui.QDoubleSpinBox(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.roll_doubleSpinBox.setFont(font)
        self.roll_doubleSpinBox.setMinimum(-360.0)
        self.roll_doubleSpinBox.setMaximum(360.0)
        self.roll_doubleSpinBox.setObjectName("roll_doubleSpinBox")
        self.gridLayout_2.addWidget(self.roll_doubleSpinBox, 1, 4, 1, 1)
        self.positionZ_doubleSpinBox = QtGui.QDoubleSpinBox(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.positionZ_doubleSpinBox.setFont(font)
        self.positionZ_doubleSpinBox.setMinimum(-1000.0)
        self.positionZ_doubleSpinBox.setMaximum(1000.0)
        self.positionZ_doubleSpinBox.setObjectName("positionZ_doubleSpinBox")
        self.gridLayout_2.addWidget(self.positionZ_doubleSpinBox, 3, 4, 1, 1)
        self.positionX_label = QtGui.QLabel(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.positionX_label.setFont(font)
        self.positionX_label.setObjectName("positionX_label")
        self.gridLayout_2.addWidget(self.positionX_label, 2, 1, 1, 1)
        self.positionZ_label = QtGui.QLabel(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.positionZ_label.setFont(font)
        self.positionZ_label.setObjectName("positionZ_label")
        self.gridLayout_2.addWidget(self.positionZ_label, 2, 4, 1, 1)
        self.positionX_doubleSpinBox = QtGui.QDoubleSpinBox(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.positionX_doubleSpinBox.setFont(font)
        self.positionX_doubleSpinBox.setMinimum(-1000.0)
        self.positionX_doubleSpinBox.setObjectName("positionX_doubleSpinBox")
        self.gridLayout_2.addWidget(self.positionX_doubleSpinBox, 3, 1, 1, 1)
        self.positionY_label = QtGui.QLabel(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.positionY_label.setFont(font)
        self.positionY_label.setObjectName("positionY_label")
        self.gridLayout_2.addWidget(self.positionY_label, 2, 2, 1, 2)
        self.positionY_doubleSpinBox = QtGui.QDoubleSpinBox(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.positionY_doubleSpinBox.setFont(font)
        self.positionY_doubleSpinBox.setMinimum(-1000.0)
        self.positionY_doubleSpinBox.setMaximum(1000.0)
        self.positionY_doubleSpinBox.setObjectName("positionY_doubleSpinBox")
        self.gridLayout_2.addWidget(self.positionY_doubleSpinBox, 3, 2, 1, 2)
        self.rateOfChange_label = QtGui.QLabel(self.transformation_groupBox)
        self.rateOfChange_label.setObjectName("rateOfChange_label")
        self.gridLayout_2.addWidget(self.rateOfChange_label, 4, 0, 1, 1)
        self.rateOfChange_horizontalSlider = QtGui.QSlider(self.transformation_groupBox)
        self.rateOfChange_horizontalSlider.setMinimum(1)
        self.rateOfChange_horizontalSlider.setMaximum(20)
        self.rateOfChange_horizontalSlider.setProperty("value", 10)
        self.rateOfChange_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rateOfChange_horizontalSlider.setObjectName("rateOfChange_horizontalSlider")
        self.gridLayout_2.addWidget(self.rateOfChange_horizontalSlider, 4, 1, 1, 1)
        self.gridLayout_7.addWidget(self.transformation_groupBox, 2, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.scaffoldFrame)
        self.mapping_groupBox = QtGui.QGroupBox(self.parameterFitPage)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.mapping_groupBox.setFont(font)
        self.mapping_groupBox.setObjectName("mapping_groupBox")
        self.gridLayout_6 = QtGui.QGridLayout(self.mapping_groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.mappingMethod_label = QtGui.QLabel(self.mapping_groupBox)
        self.mappingMethod_label.setObjectName("mappingMethod_label")
        self.gridLayout_6.addWidget(self.mappingMethod_label, 0, 0, 1, 1)
        self.map_pushButton = QtGui.QPushButton(self.mapping_groupBox)
        self.map_pushButton.setEnabled(False)
        self.map_pushButton.setObjectName("map_pushButton")
        self.gridLayout_6.addWidget(self.map_pushButton, 11, 2, 1, 1)
        self.automaticMapping_radioButton = QtGui.QRadioButton(self.mapping_groupBox)
        self.automaticMapping_radioButton.setObjectName("automaticMapping_radioButton")
        self.gridLayout_6.addWidget(self.automaticMapping_radioButton, 0, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 11, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.mapping_groupBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_6.addWidget(self.pushButton, 10, 0, 1, 1)
        self.createNode_checkBox = QtGui.QCheckBox(self.mapping_groupBox)
        self.createNode_checkBox.setEnabled(False)
        self.createNode_checkBox.setObjectName("createNode_checkBox")
        self.gridLayout_6.addWidget(self.createNode_checkBox, 8, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem4, 10, 2, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.mapping_groupBox)
        self.checkBox.setEnabled(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_6.addWidget(self.checkBox, 9, 0, 1, 1)
        self.manualMapping_radioButton = QtGui.QRadioButton(self.mapping_groupBox)
        self.manualMapping_radioButton.setObjectName("manualMapping_radioButton")
        self.gridLayout_6.addWidget(self.manualMapping_radioButton, 0, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.mapping_groupBox)
        self.plotting_groupBox = QtGui.QGroupBox(self.parameterFitPage)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.plotting_groupBox.setFont(font)
        self.plotting_groupBox.setObjectName("plotting_groupBox")
        self.gridLayout_8 = QtGui.QGridLayout(self.plotting_groupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.plot_pushButton = QtGui.QPushButton(self.plotting_groupBox)
        self.plot_pushButton.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.plot_pushButton.setFont(font)
        self.plot_pushButton.setObjectName("plot_pushButton")
        self.gridLayout_8.addWidget(self.plot_pushButton, 10, 3, 1, 1)
        self.dataType_label = QtGui.QLabel(self.plotting_groupBox)
        self.dataType_label.setObjectName("dataType_label")
        self.gridLayout_8.addWidget(self.dataType_label, 0, 0, 1, 1)
        self.ephys_radioButton = QtGui.QRadioButton(self.plotting_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.ephys_radioButton.setFont(font)
        self.ephys_radioButton.setObjectName("ephys_radioButton")
        self.gridLayout_8.addWidget(self.ephys_radioButton, 0, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem5, 10, 1, 1, 1)
        self.rnaSeq_radioButton = QtGui.QRadioButton(self.plotting_groupBox)
        self.rnaSeq_radioButton.setObjectName("rnaSeq_radioButton")
        self.gridLayout_8.addWidget(self.rnaSeq_radioButton, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.plotting_groupBox)
        self.resetButton_widget = QtGui.QWidget(self.parameterFitPage)
        self.resetButton_widget.setObjectName("resetButton_widget")
        self.gridLayout_4 = QtGui.QGridLayout(self.resetButton_widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.alignResetButton = QtGui.QPushButton(self.resetButton_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignResetButton.sizePolicy().hasHeightForWidth())
        self.alignResetButton.setSizePolicy(sizePolicy)
        self.alignResetButton.setObjectName("alignResetButton")
        self.gridLayout_4.addWidget(self.alignResetButton, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.resetButton_widget)
        self.toolBox.addItem(self.parameterFitPage, "")
        self.verticalLayout_3.addWidget(self.toolBox)
        self.frame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.viewAllButton = QtGui.QPushButton(self.frame)
        self.viewAllButton.setObjectName("viewAllButton")
        self.horizontalLayout_2.addWidget(self.viewAllButton)
        self.exportMappedButton = QtGui.QPushButton(self.frame)
        self.exportMappedButton.setObjectName("exportMappedButton")
        self.horizontalLayout_2.addWidget(self.exportMappedButton)
        self.doneButton = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doneButton.sizePolicy().hasHeightForWidth())
        self.doneButton.setSizePolicy(sizePolicy)
        self.doneButton.setObjectName("doneButton")
        self.horizontalLayout_2.addWidget(self.doneButton)
        self.verticalLayout_3.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.horizontalLayout.addWidget(self.dockWidget)
        self.sceneviewerWidget = DataMapperSceneviewerWidget(ScaffoldDataMapper)
        self.sceneviewerWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sceneviewerWidget.sizePolicy().hasHeightForWidth())
        self.sceneviewerWidget.setSizePolicy(sizePolicy)
        self.sceneviewerWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.sceneviewerWidget.setObjectName("sceneviewerWidget")
        self.horizontalLayout.addWidget(self.sceneviewerWidget)

        self.retranslateUi(ScaffoldDataMapper)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(6)
        QtCore.QMetaObject.connectSlotsByName(ScaffoldDataMapper)

    def retranslateUi(self, ScaffoldDataMapper):
        ScaffoldDataMapper.setWindowTitle(QtGui.QApplication.translate("ScaffoldDataMapper", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("ScaffoldDataMapper", "Scaffol Data Mapper", None, QtGui.QApplication.UnicodeUTF8))
        self.meshType_label.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Scaffold type:", None, QtGui.QApplication.UnicodeUTF8))
        self.parameterSet_label.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Scaffold species:", None, QtGui.QApplication.UnicodeUTF8))
        self.ephys_label.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Data:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "- including neurite, ephys, RNA-Seq", None, QtGui.QApplication.UnicodeUTF8))
        self.timeSeries_groupBox.setTitle(QtGui.QApplication.translate("ScaffoldDataMapper", "Time Sequence (active when temporal data is available)", None, QtGui.QApplication.UnicodeUTF8))
        self.timePoint_label.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Toggle time for data cloud", None, QtGui.QApplication.UnicodeUTF8))
        self.transformation_groupBox.setTitle(QtGui.QApplication.translate("ScaffoldDataMapper", "Edit Scaffold Transformation:", None, QtGui.QApplication.UnicodeUTF8))
        self.position_label.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Postions:", None, QtGui.QApplication.UnicodeUTF8))
        self.pitch_label.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Pitch", None, QtGui.QApplication.UnicodeUTF8))
        self.rotateAxis_label.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Rotation (Euler angles):", None, QtGui.QApplication.UnicodeUTF8))
        self.yaw_label.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Yaw", None, QtGui.QApplication.UnicodeUTF8))
        self.roll_label.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Roll", None, QtGui.QApplication.UnicodeUTF8))
        self.positionX_label.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.positionZ_label.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.positionY_label.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.rateOfChange_label.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Rate of change:", None, QtGui.QApplication.UnicodeUTF8))
        self.mapping_groupBox.setTitle(QtGui.QApplication.translate("ScaffoldDataMapper", "Mapping Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.mappingMethod_label.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Mapping method:", None, QtGui.QApplication.UnicodeUTF8))
        self.map_pushButton.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Map", None, QtGui.QApplication.UnicodeUTF8))
        self.automaticMapping_radioButton.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Automatic", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Remove node data", None, QtGui.QApplication.UnicodeUTF8))
        self.createNode_checkBox.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Create node data on scaffold", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Select node data on scaffold", None, QtGui.QApplication.UnicodeUTF8))
        self.manualMapping_radioButton.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.plotting_groupBox.setTitle(QtGui.QApplication.translate("ScaffoldDataMapper", "Plotting Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_pushButton.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.dataType_label.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Data type:", None, QtGui.QApplication.UnicodeUTF8))
        self.ephys_radioButton.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Time-series", None, QtGui.QApplication.UnicodeUTF8))
        self.rnaSeq_radioButton.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "RNA-Seq", None, QtGui.QApplication.UnicodeUTF8))
        self.alignResetButton.setToolTip(QtGui.QApplication.translate("ScaffoldDataMapper", "Reset the alignment settings", None, QtGui.QApplication.UnicodeUTF8))
        self.alignResetButton.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.parameterFitPage), QtGui.QApplication.translate("ScaffoldDataMapper", "Control Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.viewAllButton.setToolTip(QtGui.QApplication.translate("ScaffoldDataMapper", "Adjust the view to see the whole model", None, QtGui.QApplication.UnicodeUTF8))
        self.viewAllButton.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "View All", None, QtGui.QApplication.UnicodeUTF8))
        self.exportMappedButton.setToolTip(QtGui.QApplication.translate("ScaffoldDataMapper", "Offset the model to the centre of the data points. May need to click View All afterwards.", None, QtGui.QApplication.UnicodeUTF8))
        self.exportMappedButton.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Export Mapped Scaffold", None, QtGui.QApplication.UnicodeUTF8))
        self.doneButton.setToolTip(QtGui.QApplication.translate("ScaffoldDataMapper", "Finish this step", None, QtGui.QApplication.UnicodeUTF8))
        self.doneButton.setText(QtGui.QApplication.translate("ScaffoldDataMapper", "Exit", None, QtGui.QApplication.UnicodeUTF8))

from mapclientplugins.scaffolddatamapperstep.view.datamappersceneviewerwidget import DataMapperSceneviewerWidget
